version: 2.1
jobs:
  build_and_deploy:
    docker:
      - image: verdigristech/ci-base
    working_directory: ~/docker-aws
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to Docker Cloud
          command: echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
      - run:
          name: Build Docker image
          command: |
            export VERSION=${CIRCLE_TAG:1}
            docker build -t verdigristech/aws:${VERSION:-edge} .
            [ -n "${CIRCLE_TAG}"] && docker tag verdigristech/aws:${VERSION} verdigristech/aws:latest
      - run:
          name: Deploy container
          command: |
            export VERSION=${CIRCLE_TAG:1}
            docker push verdigristech/aws:${VERSION:-edge}
            [ -n "${CIRCLE_TAG}"] && docker push verdigristech/aws:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_deploy:
          context: common
          filters:
            tags:
              only: /v\d+(\.\d+)*/
