version: 2
jobs:
  build_and_deploy:
    docker:
      - image: verdigristech/ci-base
    working_directory: ~/docker-aws
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to Docker Cloud
          command: echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
      - run:
          name: Build Docker image
          command: docker build -t verdigristech/aws .
      # - run:
      #     name: Deploy container
      #     command: docker push verdigristech/aws

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_deploy:
          context: common
          filters:
            tags:
              only: /v\d+(\.\d+)*/
            # branches:
            #   ignore: /.*/
